"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['ScopeCapt2.py']
DATA_FILES = ['imgBase64.py', 'FreeSansBold.ttf']
OPTIONS = {'iconfile': 'img/icon/AnyConv.com_oscilloscope_512px.icns'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
